apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ajd0rl0j1-dotnet-basic 
  janus-idp.io/tekton: ajd0rl0j1-dotnet-basic
  backstage.io/kubernetes-id: ajd0rl0j1-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ajd0rl0j1-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  